NewspaperSolution.UI/Areas/Admin/Controllers/HomeController.cs
using NewspaperSolution.DataAccessLayer.Repositories.Concrete.EfRepositories;
using NewspaperSolution.EntityLayer.Entites.Concrete;
using NewspaperSolution.UI.Areas.Admin.Data.VMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewspaperSolution.UI.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        EfPostRepository _postRepository;
        public HomeController() => _postRepository = new EfPostRepository();
       
        // GET: Admin/Home
        public ActionResult HomePage(int id)
        {
            var getir = _postRepository.GetById(id);
            if (getir!= null)
            {
                return View("HomePage", getir);
            }
            else
            {
                return View("/Home/HomePage");
            }
            
        }
    }
}

NewspaperSolution.UI/Areas/Admin/Controllers/PostController.cs
using NewspaperSolution.DataAccessLayer.Repositories.Concrete.EfRepositories;
using NewspaperSolution.EntityLayer.Entites.Concrete;
using NewspaperSolution.EntityLayer.Enum;
using NewspaperSolution.UI.Areas.Admin.Data.DTOs;
using NewspaperSolution.UI.Areas.Admin.Data.VMs;
using NewspaperSolution.Utility.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewspaperSolution.UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        EfPostRepository _postRepo;
        EfAppUserRepository _appUserRepo;
        EfCategoryRepository _categoryRepo;
        EfCommentRepository _commentRepo;

        public PostController()
        {
            _postRepo = new EfPostRepository();
            _appUserRepo = new EfAppUserRepository();
            _categoryRepo = new EfCategoryRepository();
            _commentRepo = new EfCommentRepository();
        }

        // GET: Admin/Post
        public ActionResult Create()
        {
            AddPostVM data = new AddPostVM()
            {
                Categories = _categoryRepo.GetActive(),
                AppUsers = _appUserRepo.GetDefault(x => x.Role != Role.Member)
            };
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(Post data, HttpPostedFileBase Image)
        {
            List<string> UploadImagePaths = new List<string>();
            UploadImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadImagePaths[0];

            if (data.ImagePath == "1" || data.ImagePath == "2" || data.ImagePath == "3")
            {
                data.ImagePath = ImageUploader.DefaultProfileImagePath;
                data.ImagePath = ImageUploader.DefaultXSmallProfileImagePath;
                data.ImagePath = ImageUploader.DefaultCruptedProfileImagePath;
            }
            else
            {
                data.ImagePath = UploadImagePaths[1];
                data.ImagePath = UploadImagePaths[2];
            }
            _postRepo.Add(data);
            return Redirect("/Admin/Post/List");

        }

        public ActionResult List()
        {
            return View(_postRepo.GetActive());
        }
         
        public ActionResult Update(int id)
        {
            Post post = _postRepo.GetById(id);
            UpdatePostVM data = new UpdatePostVM();
            data.PostDTO.Id = post.Id;
            data.PostDTO.Header = post.Header;
            data.PostDTO.Content = post.Content;
            data.PostDTO.ImagePath = post.ImagePath;
            data.Categories = _categoryRepo.GetActive();
            data.AppUsers = _appUserRepo.GetDefault(x => x.Role != Role.Member);
            return View(data);
        }


        [HttpPost]
        public ActionResult Update (PostDTO data, HttpPostedFileBase Image)
        {
            List<string> UploadImagePaths = new List<string>();
            UploadImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadImagePaths[0];

            Post post = _postRepo.GetById(data.Id);

            if (data.ImagePath == "1" || data.ImagePath == "2" || data.ImagePath == "3")
            {
                if (post.ImagePath == null || post.ImagePath == ImageUploader.DefaultProfileImagePath)
                {
                    post.ImagePath = ImageUploader.DefaultProfileImagePath;
                    post.ImagePath = ImageUploader.DefaultXSmallProfileImagePath;
                    post.ImagePath = ImageUploader.DefaultCruptedProfileImagePath;
                }
            }
            else
            {
                post.ImagePath = UploadImagePaths[0];
                post.ImagePath = UploadImagePaths[1];
                post.ImagePath = UploadImagePaths[2];
            }

            post.Header = data.Header;
            post.Content = data.Content;
            post.CategoryId = data.CategoryId;
            post.AppUserId = data.AppUserId;
            post.Status = Status.Active;
            post.UpdateDate = DateTime.Now;
            _postRepo.Update(post);
            return Redirect("/Admin/Post/List");
        }

        public ActionResult Delete (int id)
        {
            _postRepo.Remove(id);
            return Redirect("/Admin/Post/List");
        }

        public ActionResult Details (int id)
        {
            PostDetailsVM data = new PostDetailsVM();
            data.Post = _postRepo.GetById(id);
            data.AppUser = _appUserRepo.GetById(data.Post.AppUserId);

            data.Comments = _commentRepo.GetDefault(x => x.PostId == id && x.Status != Status.Passive);

            data.CommentCount = _commentRepo.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count;

            return View(data);
        }

       
    }
}

NewspaperSolution.UI/Areas/Admin/Views/Home/HomePage.cshtml
@model NewspaperSolution.EntityLayer.Entites.Concrete.Post
@{
    ViewBag.Title = "HomePage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";
}


<style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
        width: auto;
        margin: auto;
    }
</style>
<section class="content">
    <div class="row">
        <div class="col-sm-8">
            <div class="box box-footer">
                <div class="box-header" align="center">
                    <h4 class="box-title">Admin Home Page</h4>
                </div>
                <div class="box-body">
                    <form action="/Admin/Home/HomePage" method="post" role="form" enctype="multipart/form-data">

                        <br>
                        @* Carousel *@
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                @foreach (var item in Model.ImagePath)
                                {
                                    for (int i = 0; i < Model.ImagePath.Length; i++)
                                    {
                                        <li data-target="#myCarousel" data-slide-to="i" class="active"></li>
                                        <li data-target="#myCarousel" data-slide-to="i"></li>
                                        <li data-target="#myCarousel" data-slide-to="i"></li>
                                        <li data-target="#myCarousel" data-slide-to="i"></li>
                                    }
                                }

                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">

                                <div class="item active">
                                    <img src="~/Content/Uploads/Images/1.jpg" alt="Chania" width="100" height="100">
                                    <div class="carousel-caption">
                                        <h3>Chania</h3>
                                        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="~/Content/Uploads/Images/2.jpg" alt="Chania" width="460" height="345">
                                    <div class="carousel-caption">
                                        <h3>Chania</h3>
                                        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="~/Content/Uploads/Images/3533QTxo.jpg" alt="Flower" width="460" height="345">
                                    <div class="carousel-caption">
                                        <h3>Flowers</h3>
                                        <p>Beatiful flowers in Kolymbari, Crete.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="~/Content/Uploads/Images/4.jpg" alt="Flower" width="460" height="345">
                                    <div class="carousel-caption">
                                        <h3>Flowers</h3>
                                        <p>Beatiful flowers in Kolymbari, Crete.</p>
                                    </div>
                                </div>

                            </div>

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>

                        @* Content *@

                        <br />
                        <br />
                        <br />
                        <br />

                        <div class="box-header" align="center">
                            <h4 class="box-title">Haber Başlığı</h4>
                        </div>
                        <br />
                        <br />
                       
                        <div class="row mt-2">
                            @using (Html.BeginForm("List", "Post", FormMethod.Post))
                            {
                                <div class="col-sm-4">
                                    <div class="card">
                                        <div class="card-header">
                                            <img src="@Model.ImagePath" class="card-img-top">
                                        </div>
                                        <div class="card-body">
                                             <h3 class="card-title">@Model.Header</h3>
                                            <p class="card-text">@Model.Content</p>
                                        </div>
                                        <div class="card-footer">
                                            <a href="https://en.wikipedia.org/wiki/Battle_of_Waterloo" class="btn btn-dark btn-block">Wikipedia</a>
                                        </div>
                                    </div>
                                </div>
                            }

                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-header">
                                        <img src="img/Battle_of_Waterloo_1815.png" class="card-img-top">
                                    </div>
                                    <div class="card-body">
                                        <h5 class="card-title">Battle of Waterloo</h5>
                                        <p class="card-text">The Battle of Waterloo was fought on Sunday, 18 June 1815, near Waterloo in Belgium, part of the United Kingdom of the Netherlands at the time. A French army under the command of Emperor Napoleon Bonaparte was defeated by two of the armies of the Seventh Coalition, a British-led coalition consisting of units from the United Kingdom, the Netherlands, Hanover, Brunswick and Nassau, under the command of the Duke of Wellington, referred to by many authors as the Anglo-allied army or Wellington's army, and a Prussian army under the command of Field Marshal von Blücher, referred also as Blücher's army. The battle marked the end of the Napoleonic Wars.</p>
                                    </div>
                                    <div class="card-footer">
                                        <a href="https://en.wikipedia.org/wiki/Battle_of_Waterloo" class="btn btn-dark btn-block">Wikipedia</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-header">
                                        <img src="img/Battle_of_Waterloo_1815.png" class="card-img-top">
                                    </div>
                                    <div class="card-body">
                                        <h5 class="card-title">Battle of Waterloo</h5>
                                        <p class="card-text">The Battle of Waterloo was fought on Sunday, 18 June 1815, near Waterloo in Belgium, part of the United Kingdom of the Netherlands at the time. A French army under the command of Emperor Napoleon Bonaparte was defeated by two of the armies of the Seventh Coalition, a British-led coalition consisting of units from the United Kingdom, the Netherlands, Hanover, Brunswick and Nassau, under the command of the Duke of Wellington, referred to by many authors as the Anglo-allied army or Wellington's army, and a Prussian army under the command of Field Marshal von Blücher, referred also as Blücher's army. The battle marked the end of the Napoleonic Wars.</p>
                                    </div>
                                    <div class="card-footer">
                                        <a href="https://en.wikipedia.org/wiki/Battle_of_Waterloo" class="btn btn-dark btn-block">Wikipedia</a>
                                    </div>
                                </div>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</section>